# Generated by Django 3.1.5 on 2023-01-04 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20230103_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_queries', to='db.connection'),
        ),
        migrations.AlterField(
            model_name='query',
            name='excel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excel_queries', to='db.exceldata'),
        ),
        migrations.AlterField(
            model_name='query',
            name='json',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='json_queries', to='db.jsondata'),
        ),
        migrations.AlterField(
            model_name='query',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_queries', to='db.project'),
        ),
    ]
