# Generated by Django 3.1.5 on 2023-01-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20230103_2055'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jsondata',
            unique_together=set(),
        ),
    ]
