# Generated by Django 3.1.5 on 2023-01-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20230104_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='token_status',
            field=models.BooleanField(default=False),
        ),
    ]
