# Generated by Django 3.1.5 on 2023-01-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_tenantuser_token_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='tenant_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
