# Generated by Django 3.1.5 on 2023-01-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_tenantuser_tenant_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='username',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
