# Generated by Django 3.1.5 on 2023-01-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_tenantinvitation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together=set(),
        ),
    ]
