# Generated by Django 3.1.5 on 2023-02-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_tenantintegration_tenantuserloginconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='dflux_using',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='team_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
