# Generated by Django 3.1.5 on 2023-02-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_tenantuser_has_onboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='tenantuser',
            unique_together=set(),
        ),
    ]
