# Generated by Django 3.1.5 on 2023-04-14 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_auto_20230221_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantintegration',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_integrations', to='db.tenant'),
        ),
    ]
