# Version of docker-compose
version: "3.4"

# Containers we are going to run
services:
  api:
    image: dflux-api
    # The build parameters for this container.
    # Here we define that it should build from the current directory
    build:
      context: ./
    ports:
      - "80:8000"
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=amqp://admin:mypass@rabbitmq:5672//
      - REDIS_URL=redis://redis:6379
    depends_on:
      - rabbitmq
      - redis

  rabbitmq:
    hostname: rabbitmq
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "15672:15672"
      - "5672:5672"

  celery:
    build: ./
    command: celery -A dflux worker -l info
    environment:
      - CELERY_BROKER_URL=amqp://admin:mypass@rabbitmq:5672//
      - REDIS_URL=redis://redis:6379
    depends_on:
      - api
      - rabbitmq
      - redis

  celery-beat:
    build: ./
    command: celery -A dflux  beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - CELERY_BROKER_URL=amqp://admin:mypass@rabbitmq:5672//
      - REDIS_URL=redis://redis:6379
    depends_on:
      - api
      - rabbitmq
      - redis
  redis:
    image: redis:alpine
